# Description

Exactly the same code as in `08`, but here I run the notebook in a different machine (desktop).

# Remove pycache dir

In [1]:
!echo ${CODE_DIR}

/opt/code


In [2]:
!find ${CODE_DIR} -regex '^.*\(__pycache__\)$' -print

/opt/code/libs/clustermatch/__pycache__


In [3]:
!find ${CODE_DIR} -regex '^.*\(__pycache__\)$' -exec rm -rf {} \;

find: ‘/opt/code/libs/clustermatch/__pycache__’: No such file or directory


In [4]:
!find ${CODE_DIR} -regex '^.*\(__pycache__\)$' -print

# Modules

In [5]:
import numpy as np

from clustermatch.coef import _cm

# Settings

In [6]:
N_REPS = 10

In [7]:
np.random.seed(0)

# Setup

In [8]:
# let numba compile all the code before profiling
_cm(np.random.rand(10), np.random.rand(10))

(array([0.15625]),
 array([[0, 1]], dtype=uint64),
 array([[[0, 1, 1, 0, 0, 1, 0, 1, 1, 0],
         [1, 2, 1, 1, 0, 2, 0, 2, 2, 0]],
 
        [[1, 0, 0, 1, 0, 0, 0, 1, 1, 1],
         [2, 1, 1, 2, 0, 0, 0, 2, 1, 2]]], dtype=int16))

# Run with `n_samples` small

In [9]:
N_SAMPLES = 100

In [10]:
x = np.random.rand(N_SAMPLES)
y = np.random.rand(N_SAMPLES)

In [11]:
def func():
    for i in range(N_REPS):
        # py_func accesses the original python function, not the numba-optimized one
        # this is needed to be able to profile the function
        _cm(x, y)

In [12]:
%%timeit -n1 -r7 func()
func()

54 ms ± 10.5 ms per loop (mean ± std. dev. of 4 runs, 1 loop each)


In [13]:
%%prun -s cumulative -l 20 -T 09-n_samples_small.txt
func()

 
*** Profile printout saved to text file '09-n_samples_small.txt'. 


**UPDATE**

# Run with `n_samples` large

In [14]:
N_SAMPLES = 100000

In [15]:
x = np.random.rand(N_SAMPLES)
y = np.random.rand(N_SAMPLES)

In [16]:
def func():
    for i in range(N_REPS):
        # py_func accesses the original python function, not the numba-optimized one
        # this is needed to be able to profile the function
        _cm(x, y)

In [17]:
%%timeit -n1 -r7 func()
func()

5.08 s ± 21 ms per loop (mean ± std. dev. of 4 runs, 1 loop each)


In [18]:
%%prun -s cumulative -l 20 -T 09-n_samples_large.txt
func()

 
*** Profile printout saved to text file '09-n_samples_large.txt'. 


**UPDATE**